### ISSUE TITLE
Image behavior when dropped

### ISSUE THREAD

**Issue by Bronnium** [Bronnium/fiverr-flutter#2]
Images that have been dragged and successfully dropped shall not be available in the orange selection menu and no extra gap shall be created between the images.

![chrome_JQ4Pewmbw7](https://user-images.githubusercontent.com/1513450/195167680-ed642614-8b29-4118-881f-f0530cfc1c87.png)

**Comment by Usamamajid13** [comment]
This issue has been resolved.
