### ISSUE TITLE
Image behavior when removing from drop target

### ISSUE THREAD

**Issue by Bronnium** [Bronnium/fiverr-flutter#3]
When the "X" is clicked on the image, the corresponding image shall pop in the middle of the screen in the orange menu.

![chrome_1TLP2e8apq](https://user-images.githubusercontent.com/1513450/195169461-032311d8-2444-487b-8219-56e3af417517.png)

**Comment by Usamamajid13** [comment]
This issue has been resolved But the removed item is placed at the last of the list not in the centre.
