### ISSUE TITLE
Ipad resolution of the drag screen

### ISSUE THREAD

**Issue by Bronnium** [Bronnium/fiverr-flutter#5]
For an Ipad Air resolution 1180*820 in landscape mode, the selection menu shall be bigger and centered in the sections defined below (approximately ⅔ for the red section and ⅓ for the blue section).

![brave_u9QylgsyT3](https://user-images.githubusercontent.com/1513450/195169920-79742634-4bdc-4227-896f-364b9f10b146.png)

**Comment by Usamamajid13** [comment]
This issue has been resolved.
